services:

  app:
    image: my_airtable_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_airtable_api
    restart: on-failure:5
    logging:
      options:
        max-size: 50m
    environment:
      - TZ=Europe/Paris
    ports:
          - "8000:8000"
    env_file:
          - .env
    depends_on:
      - db
    volumes:
      - .:/app


  db:
    image: postgres:latest
    container_name: my_airtable_api_db
    restart: always
    shm_size: 128mb
    ports: 
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: