# Generated by Django 4.2 on 2025-06-18 10:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='nom')),
                ('prenom', models.CharField(max_length=50, verbose_name='prénom')),
                ('societe', models.CharField(max_length=50, null=True, verbose_name='société')),
                ('telephone', models.CharField(max_length=10, verbose_name='téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('adresse', models.CharField(max_length=200, verbose_name='adresse')),
                ('code_postal', models.CharField(max_length=5, verbose_name='code postal')),
                ('ville', models.CharField(max_length=100, verbose_name='ville')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='libellé')),
                ('duree_intervention', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='durée')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='prix unitaire')),
                ('forfait', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='forfait')),
                ('is_forfait', models.BooleanField(default=False, verbose_name='is_forfait')),
                ('date_creation', models.DateField(default=django.utils.timezone.now, verbose_name='date de création')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('categorie', models.CharField(choices=[('MECA_BCR', 'Méca BCR'), ('MECA_CBC', 'Méca CBC'), ('CARROSSERIE', 'Carrosserie'), ('CUSTOM', 'Personnalisée')])),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de demande ')),
                ('remarque', models.TextField(null=True, verbose_name='remarque')),
                ('priorite', models.CharField(choices=[('NON_PRIORITAIRE', 'Non prioritaire'), ('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], verbose_name='priorité')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mission.client', verbose_name='client')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50, verbose_name='marque')),
                ('modele', models.CharField(max_length=50, verbose_name='modèle')),
                ('immatriculation', models.CharField(max_length=9, verbose_name='immatriculation')),
                ('numero_serie', models.CharField(max_length=17, unique=True, verbose_name='numéro de série')),
                ('mise_circulation', models.DateField(null=True, verbose_name='date de mise en circulation')),
                ('kilometrage', models.IntegerField(verbose_name='kilométrage')),
                ('remarque', models.TextField(null=True, verbose_name='Remarque')),
                ('vo', models.BooleanField(verbose_name='vo')),
                ('boite_vitesse', models.CharField(verbose_name='boite de visse')),
                ('carburant', models.CharField(verbose_name='carburant')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MissionIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_supplementaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='durée supplémentaire')),
                ('taux', models.CharField(choices=[('HORAIRE', 'Horaire'), ('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3')], verbose_name='taux horaire')),
                ('cout_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.intervention', verbose_name='intervention')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.mission', verbose_name='mission')),
            ],
            options={
                'verbose_name': 'mission_intervention',
                'verbose_name_plural': 'missions_interventions',
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='interventions',
            field=models.ManyToManyField(blank=True, related_name='missions', through='mission.MissionIntervention', to='mission.intervention', verbose_name='interventions'),
        ),
        migrations.AddField(
            model_name='mission',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.vehicule', verbose_name='véhicule'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
        migrations.AlterUniqueTogether(
            name='missionintervention',
            unique_together={('mission', 'intervention')},
        ),
        migrations.AlterUniqueTogether(
            name='mission',
            unique_together={('vehicule', 'client')},
        ),
    ]
