# Generated by Django 4.2 on 2025-06-25 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_modification',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='date de modification'),
        ),
    ]
