# Generated by Django 5.2.3 on 2025-06-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_intervention_date_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='date_modification',
            field=models.DateField(null=True, verbose_name='date de modification'),
        ),
    ]
