# Generated by Django 5.2.3 on 2025-06-26 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_alter_intervention_date_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='kilometrage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='kilométrage'),
        ),
    ]
