# Generated by Django 5.2.3 on 2025-06-27 10:21

import mission.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_alter_intervention_date_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='duree_intervention',
            field=mission.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='durée'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='forfait',
            field=mission.models.PositiveDecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='forfait'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='prix_unitaire',
            field=mission.models.PositiveDecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, verbose_name='prix unitaire'),
        ),
        migrations.AlterField(
            model_name='missionintervention',
            name='cout_total',
            field=mission.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='missionintervention',
            name='duree_supplementaire',
            field=mission.models.PositiveDecimalField(decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='durée supplémentaire'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='boite_vitesse',
            field=models.CharField(verbose_name='boite de vitesse'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='kilometrage',
            field=models.PositiveIntegerField(default=0, verbose_name='kilométrage'),
        ),
    ]
