# Generated by Django 5.2.3 on 2025-06-26 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_alter_vehicule_kilometrage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='kilometrage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(72.0)], verbose_name='kilométrage'),
        ),
    ]
